services:
  web:
    container_name: ProfileService
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENV=dev
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true
